GSG-G8/ca-wiki

.travis.yml
package.json

Add Travis CI configurations to `.travis.yml` and build script to `package.json`.
Relates #10

Configure Travis CI

---

server/database/config/fakeData.sql

- insert a fake data in the data base to use it in testing .
relates #31

  fake dadata base

---

server/controllers/index.js
server/controllers/middlewares/errorHandle/error.js
server/controllers/middlewares/errorHandle/index.js

Add client and server errors handling as a middleware at `error.js` and require them at `controllers/index.js`
Relates #42

Client and server errors handling

---

.eslintrc.json
server/controllers/index.js
server/controllers/routes/admin/cohort/deleteCohort.js
server/controllers/routes/admin/cohort/index.js
server/controllers/routes/admin/index.js
server/database/queries/cohort/deleteCohort.js
server/database/queries/cohort/index.js
server/database/queries/index.js
test/index.test.js

relates #29
-  create query function that delete specific cohort data from cohort table in the database based on id which came from params.
- create the necessary middleware for this function to work in addition to handling the required /cohorts/:cohortid route.
- create a test for this route.
- send request by postman

handle Delete cohort route

---

package.json
server/app.js
server/controllers/index.js
server/controllers/middlewares/errorHandle/error.js
server/controllers/middlewares/errorHandle/index.js
test/index.test.js

- fix error handle based on issue #52 
- change beforeAll >  beforeEach in test file
- change test script in package.json file

52 fix error, modify test script

---

.eslintrc.json
server/controllers/index.js
server/controllers/routes/user/cohort/getCohortsData.js
server/controllers/routes/user/cohort/index.js
server/controllers/routes/user/index.js
server/database/queries/cohort/getCohorts.js
server/database/queries/cohort/index.js
server/database/queries/index.js
test/index.test.js

- create a query function that get all cohorts 
- create a middleware for query function to work in addition to handling the required  /cohorts 
- create a test for this route
- send request by postman
relates #14

 make get /cohort route

---

server/app.js
server/controllers/routes/admin/index.js
server/controllers/routes/admin/logout.js

Revert "20 logout"

---

server/app.js
server/controllers/routes/admin/index.js
server/controllers/routes/admin/logout.js

Logout route

---

server/controllers/routes/admin/cohort/deleteCohort.js
server/controllers/routes/admin/index.js
server/controllers/routes/admin/project/addProject.js
server/controllers/routes/admin/project/editProject.js
server/controllers/routes/admin/project/getCohortProjects.js
server/controllers/routes/admin/stats.js
server/controllers/routes/user/index.js
server/controllers/routes/user/project/getProjectsByType.js
server/controllers/routes/user/student/getAlumni.js
server/controllers/routes/user/student/getStudentById.js
server/controllers/routes/user/student/index.js
server/database/queries/index.js
server/database/queries/student/getStudentByIdQuery.js
server/database/queries/student/index.js
server/validation/editCohort.js
server/validation/generalSchema.js
server/validation/index.js
test/alumni.test.js
test/cohort.test.js
test/index.test.js

I handled route /alumni/:studentId with the covering tests
I made extra tests for uncoveres error lines
I organized the tests
Relates #64

Get Alumni/studentId

---

server/controllers/routes/user/index.js
server/controllers/routes/user/project/getStudentProject.js
server/controllers/routes/user/project/index.js
server/database/queries/index.js
server/database/queries/project/index.js
server/database/queries/project/studentProjectQuery.js
test/index.test.js

relates #65
- create route  /projects/:projectId/alumni
- make a query to get all student for a specific project
- make function needed for this route
- make test needed for this route
- send requests by postman

hanlde route /projects/:projectId/alumni

---

server/app.js
server/controllers/admin/login.js
server/routes/admin.js

95 back end notes

---

client/package-lock.json
client/package.json

install babel-plugin-import as dependencies

install babel-plugin-import as dependencies

---

client/package-lock.json
client/src/components/AdminContainer/index.js
client/src/components/AdminContainer/style.css

Display Back button to go back like the browser back button when not in home path and decide whether show button or not.

115 display back button

---

server/controllers/admin/AssignProjectStudent.js
server/controllers/admin/index.js
server/controllers/index.js
server/database/queries/index.js
server/database/queries/student/AssignProjectStudentQuery.js
server/database/queries/student/index.js
server/routes/admin.js
server/utils/index.js
server/utils/validation/index.js
server/utils/validation/studentProjectSchema.js
test/alumni.test.js

- I created a DB query which insert values to `student_project` table.
- The function will check if we have student 4 exist it will insert 4 values, else if student 3 exist it will insert 3 values for the 3 students and so on.
- I handled the route `/Alumni/projects/assign` with a function will validate the coming data with a schema.
- I wrote tests for the success case and the failed one.
Relates #142

Assign projects to students

---

client/src/containers/SearchPage/index.js

make condition to Gaza cohort name because it was like fakg3, and make a condition to render student projects
relates #147

fix bug in search page

---

client/src/components/UserContainer/index.js

fix bugs in NavLink

---

client/src/components/Charts/dayVisitsReport.js
client/src/components/Charts/pageviewReport.js
client/src/components/Charts/queryReport.js
client/src/googleAuth/authUtils.js
client/src/googleAuth/getSecrets.js
server/controllers/admin/getSecret.js
server/controllers/admin/index.js
server/controllers/index.js
server/routes/admin.js

I created a protected route when you ask for it's data it will send data from the server environment and I changed the way the variables was used at the react component from taking it directly from the react unprotected environment into GET it from protected route using axios and changing the functions into async/await functions

Handling protected route for secret env variables

---

server/database/queries/student/getStudentProjects.js

relates #164
fix bug in route
```router.get('/alumni/:studentId/projects', getStudentProjects);```
in getStudentProjects.js 
the data come back have error because problem of query

fix bug in getStudentProjects.js query

---

client/src/containers/CohortProjectsPage/index.js
client/src/containers/UserProjectPage/index.js

fix bug in main menu navigation when you go from internal project to remotely projct relates
relates #167

fix bug in main menu navigation

---

client/package-lock.json
client/package.json
client/src/containers/SearchPage/index.js
client/src/containers/SearchPage/style.css

relates #160
make style for search page

make style for search page

---

client/src/components/AdminContainer/index.js
client/src/components/UserContainer/index.js
client/src/containers/ProjectDetailsPage/index.js
client/src/containers/SearchPage/style.css

#169 
modify Pagination in search page
fix bug in main menu nav link
add links to student name in projects page
add link to logo in admin pages

169 enhancement

---

client/src/containers/AdminCohortPage/index.js
client/src/containers/AdminProjectPage/index.js
client/src/containers/AdminStudentPage/index.js
client/src/containers/CohortProjectsPage/index.js
client/src/containers/SearchPage/index.js
client/src/containers/SpecificAlumnusPage/index.js

make loading page in admin cohort page 
make loading page in student cohort page
make loading page in project page 
make loading page in user-specific alumni page
make loading page in user cohort projects page
make loading page in search page page

171 loading page

---

README.md
client/src/containers/HomePage/index.js

edit home page content and the read me

---

client/src/components/AdminContainer/index.js
client/src/containers/CohortsAlumniPage/index.js

I fixed `goBack` function bug and `activeItemIndex` value bug as I mentioned in issue #173

173 fix bugs
